 

  - name: 'create dbhome'
    become: 'true'
    become_user: 'root'
    become_method: 'sudo'
    shell:  |
      {{ dbaascli_path }} dbhome create --version {{ version_tag }} --oracleHomeName {{ db_home_name }}
    register: 'dbhome_create_result'
    failed_when: dbhome_create_result.stdout | regex_search("ERROR:.+")
    async: 5400
    poll: 120
  - debug: { msg: '{{ dbhome_create_result }}' }

  - name: 'DB Home Info'
    include_tasks: 'dbhome_info.yml'