- name: 'Check Client Prerequisites'
  become: 'true'
  become_user: 'oracle'
  become_method: 'sudo'
  shell: |
    ssh -i {{ identity_file }} -o "StrictHostKeyChecking=no" opc@{{ target_node }} -t "rpm -qa | egrep 'dbaas'"
  register: 'check_client_prereq_result'
- debug: { msg: '{{ check_client_prereq_result }}' }

- name: 'Setting dbaas, fpe, and fpptools versions'
  set_fact:
    dbaas_version: '{{ check_client_prereq_result.stdout | regex_findall("dbaas.+?-(.+)\b") | first }}'
    
- name: 'Assert that dbaas, fpe, and fpp server tools are the correct versions'
  assert:
    that: 
      - dbaas_version is version('1.0-1+21.1.1.3.0_210630.1055', '>=')
     
    quiet: 'true'
