- name: 'Query Working Copy {{ wc_name }} for overall patch status'
  become: 'true'
  become_user: 'oracle'
  become_method: 'sudo'
  shell: |
    {{ rhpctl_path }} query workingcopy -workingcopy {{ wc_name }} -details '' 
  ignore_errors: '{{ ignore_errors_flag }}'
  register: 'query_wc_result'
- debug:
    msg: '{{ query_wc_result }}'
- set_fact:
    completion_status: '{{ query_wc_result.stdout | regex_search("Software only\: false") }}'
- debug:
    msg: '{{ completion_status }}'